TykTechnologies/graphql-go-tools

pkg/graphql/complexity.go, pkg/graphql/request.go, pkg/graphql/request_test.go, pkg/middleware/operation_complexity/operation_complexity.go, pkg/middleware/operation_complexity/operation_complexity_test.go
fixes https://github.com/TykTechnologies/product/issues/298
=> implement initial default complexity calculator

pkg/execution/datasource/datasource.go, pkg/execution/datasource/datasource_graphql.go, pkg/execution/datasource/datasource_http_json.go
Reverts TykTechnologies/graphql-go-tools#41
=> Revert "Add json tags to type field configuration fields"

pkg/execution/datasource/datasource.go, pkg/execution/datasource/datasource_graphql.go, pkg/execution/datasource/datasource_http_json.go, pkg/execution/datasource_http_json_test.go, pkg/execution/execution_test.go, pkg/execution/planning_test.go, pkg/graphql/execution_engine_test.go
Related to https://github.com/TykTechnologies/tyk/issues/3127
=> remove host field from httpjson and graphql data source

pkg/playground/fixtures/handlers.golden, pkg/playground/playground.go, pkg/playground/playground_test.go
Related to https://github.com/TykTechnologies/tyk-analytics-ui/issues/2084
=> Make playground files urls relative path

pkg/asttransform/baseschema_test.go, pkg/asttransform/fixtures/custom_query_name.golden, pkg/graphql/schema.go, pkg/graphql/schema_test.go
related to https://github.com/TykTechnologies/product/issues/337
=> fix usage of constant query type name and add helpers

pkg/astvalidation/definition_validation.go, pkg/astvalidation/definition_validation_test.go, pkg/astvalidation/rule_known_type_names.go, pkg/astvalidation/rule_known_type_names_test.go, pkg/astvalidation/rule_unique_enum_value_names.go, pkg/astvalidation/rule_unique_enum_value_names_test.go, pkg/astvalidation/rule_unique_field_definition_names.go, pkg/astvalidation/rule_unique_field_definition_names_test.go, pkg/astvalidation/rule_unique_operation_types.go, pkg/astvalidation/rule_unique_operation_types_test.go, pkg/astvalidation/rule_unique_type_names.go, pkg/astvalidation/rule_unique_type_names_test.go, pkg/graphql/errors.go, pkg/graphql/errors_test.go, pkg/graphql/schema.go, pkg/graphql/schema_test.go, pkg/operationreport/externalerror.go
Related to https://github.com/TykTechnologies/product/issues/285
=> schema validation

pkg/ast/ast.go, pkg/ast/ast_test.go, pkg/astimport/astimport.go, pkg/astimport/astimport_test.go, pkg/execution/datasource/datasource.go, pkg/execution/datasource/datasource_graphql.go, pkg/execution/datasource/datasource_http_json.go, pkg/execution/datasource/datasource_http_polling_stream.go, pkg/execution/datasource/datasource_mqtt.go, pkg/execution/datasource/datasource_pipeline.go, pkg/execution/datasource_graphql_test.go, pkg/execution/handler.go, pkg/execution/planning.go
related to https://github.com/TykTechnologies/product/issues/347
=> fix multi queries with same argument

pkg/execution/datasource/datasource.go, pkg/execution/datasource/datasource_graphql.go, pkg/execution/datasource/datasource_http_json.go
Related to https://github.com/TykTechnologies/tyk/issues/3235
=> Add bson tags to fields

pkg/execution/datasource/datasource.go, pkg/execution/datasource/datasource_graphql.go, pkg/execution/datasource/datasource_http_json.go, pkg/execution/datasource/hooks.go, pkg/execution/datasource_graphql_test.go, pkg/execution/datasource_http_json_test.go, pkg/execution/planning_test.go, pkg/graphql/execution_engine.go
Closes https://github.com/TykTechnologies/product/issues/363
=> Add datasource hooks

go.mod, go.sum, pkg/execution/datasource/datasource.go, pkg/execution/datasource_http_json_test.go
Regarding https://github.com/TykTechnologies/tyk/issues/3235
=> Ensure bson json compatibility

pkg/graphql/normalization.go, pkg/graphql/normalization_test.go, pkg/starwars/starwars.go, pkg/starwars/testdata/queries/multi_queries_with_arguments.query, pkg/starwars/testdata/star_wars.graphql
closes https://github.com/TykTechnologies/product/issues/375
=> fix extracting variables with multiple queries on contract

pkg/graphql/request_fields_validator.go, pkg/graphql/request_fields_validator_test.go
This PR does not break current functionality. 
Missing tests have also been added.
=> Add logic to block or allow fields by list (TT-1097)

pkg/playground/playground.go, pkg/playground/playground_test.go
I saw a problem while raising this PR: https://github.com/TykTechnologies/tyk/pull/3486
=> Fix playgroundURL trailing slash appending for some cases

pkg/graphql/schema.go, pkg/graphql/schema_test.go
This PR adds a normalization API to the schema struct.
=> add normalization to schema

pkg/ast/ast_field.go, pkg/astparser/parser.go, pkg/astparser/parser_test.go, pkg/engine/datasource/graphql_datasource/graphql_datasource.go, pkg/engine/datasource/graphql_datasource/graphql_datasource_test.go, pkg/engine/datasource/rest_datasource/rest_datasource.go, pkg/engine/datasource/rest_datasource/rest_datasource_test.go, pkg/engine/datasource/staticdatasource/static_datasource.go, pkg/engine/datasource/staticdatasource/static_datasource_test.go, pkg/engine/datasourcetesting/datasourcetesting.go, pkg/engine/plan/plan.go, pkg/engine/plan/plan_closer_test.go, pkg/engine/plan/plan_test.go, pkg/engine/resolve/defer_test.go, pkg/engine/resolve/resolve.go, pkg/engine/resolve/resolve_mock_test.go, pkg/engine/resolve/resolve_test.go, pkg/postprocess/datasourceinput_test.go, pkg/postprocess/defer_test.go, pkg/postprocess/postprocess_test.go
- Move processing of response data from datasource into resolver
- Add error locations
- Add errors when unable to resolve a field
- Add merging of upstream datasource errors
=> Refactor resolver

pkg/graphql/normalization_test.go
for more info check https://tyktech.atlassian.net/browse/TT-2721
=> TT-2721: tests for unused optional variables

pkg/ast/ast_description.go, pkg/astprinter/astprinter_test.go, pkg/astprinter/testdata/starwars.schema.graphql
original PR https://github.com/jensneuse/graphql-go-tools/pull/266
=> Jobergner fix indentation within multiline comments

pkg/ast/ast_variable_definition.go, pkg/astnormalization/astnormalization.go, pkg/astnormalization/astnormalization_test.go, pkg/astnormalization/variables_default_value_extraction.go, pkg/astnormalization/variables_default_value_extraction_test.go, pkg/astvalidation/astvalidation_test.go, pkg/engine/datasource/introspection_datasource/input.go, pkg/engine/datasource/introspection_datasource/input_test.go, pkg/engine/datasource/introspection_datasource/planner_test.go, pkg/engine/datasource/introspection_datasource/source.go, pkg/engine/datasource/introspection_datasource/source_test.go, pkg/engine/datasourcetesting/datasourcetesting.go, pkg/engine/plan/plan.go, pkg/engine/resolve/variable.go, pkg/graphql/execution_engine_test.go, pkg/graphql/execution_engine_v2_test.go
- Fix introspection tests
- Fix getting root value type
- Add default arguments values extraction normalizer
=> fix introspection tests

internal/pkg/unsafebytes/unsafebytes.go, pkg/ast/ast_val_int_value.go, pkg/ast/path.go, pkg/engine/plan/plan.go, pkg/execution/planning.go, pkg/middleware/operation_complexity/operation_complexity.go
This PR includes changes to fix [code scanning alerts](https://github.com/TykTechnologies/graphql-go-tools/security/code-scanning?query=branch%3Amaster+is%3Aopen+).  
You can find an explanation about the alerts here: https://codeql.github.com/codeql-query-help/go/go-incorrect-integer-conversion/
=> Review and fix/close GitHub code scanning issues identified (TT-4586)

pkg/engine/datasource/graphql_datasource/graphql_datasource.go, pkg/engine/datasource/graphql_datasource/graphql_datasource_test.go
PR for [TT-4630](https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/26?modal=detail&selectedIssue=TT-4630)
=> Fix addVariableDefinitionsRecursively to handle arrays inside objects(TT-4630)

pkg/engine/plan/local_type_field_extractor.go, pkg/engine/plan/local_type_field_extractor_test.go, pkg/engine/plan/required_field_extractor.go
PR for [TT-4629](https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/26?modal=detail&selectedIssue=TT-4629)
=> Don't include all external fields in a type's child fields. (TT-4629)

pkg/engine/datasource/graphql_datasource/batch.go, pkg/engine/resolve/dataloader.go, pkg/engine/resolve/dataloader_test.go
PR for [TT-4778](https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/26?modal=detail&selectedIssue=TT-4778)
=> Fix data loader heterogeneous types (TT-4778)

examples/kafka_pubsub/README.md, examples/kafka_pubsub/tyk-api-definition.json
I added a full copy of the Tyk API definition for Kafka data source example.
=> [TT-4370] Add a full copy of Tyk API definition and extend the document.

pkg/astnormalization/definition_normalization.go, pkg/astnormalization/definition_normalization_test.go, pkg/astnormalization/enum_type_extending.go, pkg/astnormalization/input_object_type_extending.go, pkg/astnormalization/interface_type_extending.go, pkg/astnormalization/object_type_extending.go, pkg/astnormalization/scalar_type_extending.go, pkg/astnormalization/union_type_extending.go, pkg/federation/sdlmerge/enum_type_extending.go, pkg/federation/sdlmerge/enum_type_extending_test.go, pkg/federation/sdlmerge/input_type_extending.go, pkg/federation/sdlmerge/input_type_extending_test.go, pkg/federation/sdlmerge/interface_type_extending.go, pkg/federation/sdlmerge/interface_type_extending_test.go, pkg/federation/sdlmerge/object_type_extending.go, pkg/federation/sdlmerge/object_type_extending_test.go, pkg/federation/sdlmerge/scalar_type_extending.go, pkg/federation/sdlmerge/scalar_type_extending_test.go, pkg/federation/sdlmerge/sdlmerge.go, pkg/federation/sdlmerge/sdlmerge_test.go, pkg/federation/sdlmerge/union_type_extending.go, pkg/federation/sdlmerge/union_type_extending_test.go
[changelog]
internal: Subgraphs are normalized before merge; added missing extension handlers.
=> [TT-5199] Subgraphs are normalized before a merge is attempted.

examples/kafka_pubsub/README.md, examples/kafka_pubsub/docker-compose.yml, examples/kafka_pubsub/kafka_jaas.conf, examples/kafka_pubsub/main.go
A simple example for testing SASL.
=> [TT-5562] SASL Example for Kafka data source

pkg/astnormalization/inject_input_default_values.go, pkg/astnormalization/inject_input_default_values_test.go
https://tyktech.atlassian.net/browse/TT-5563
[changelog]
fix inject input default and support list of custom scalar
=> fix inject input default and support list of custom scalar

examples/kafka_pubsub/main.go
Log error messages and inform the user accurately.
Sample:
```
Failed to enqueue message: {"stock":{"name":"product1","price":3354,"in_stock":721}}, error: kafka: Failed to produce message to topic test.topic.product1: kafka server: Tried to send a message to a replica that is not the leader for some partition. Your metadata is out of date.
```
=> Improve error handling and logging of Sarama async producer.

pkg/engine/datasource/kafka_datasource/kafka_datasource_test.go
Fix broken Kafka data source tests
=> [TT-6022] Fix broken Kafka data source tests

pkg/engine/datasource/graphql_datasource/graphql_datasource.go, pkg/engine/datasource/graphql_datasource/graphql_datasource_test.go, pkg/engine/datasource/graphql_datasource/graphql_subscription_client.go, pkg/engine/datasource/graphql_datasource/graphql_subscription_client_test.go, pkg/engine/datasource/graphql_datasource/graphql_tws_handler_test.go, pkg/engine/datasource/graphql_datasource/graphql_ws_handler_test.go, pkg/engine/datasource/graphql_datasource/graphql_ws_proto_types.go
This PR modifies the latest changes to the subscription implementations
=> adjust new subscription protocol changes

pkg/engine/datasource/graphql_datasource/graphql_datasource.go, pkg/engine/datasource/graphql_datasource/graphql_datasource_test.go, pkg/engine/plan/plan.go
* add broken testcase for single __typename field on union
* fix resolving __typename as root field of GraphQL datasource
=> fix: resolve __typename as root field

pkg/engine/datasource/graphql_datasource/graphql_datasource.go, pkg/engine/datasource/graphql_datasource/graphql_datasource_test.go
* feat: planner, support custom scalar fields
* chore: fix test
Co-authored-by: Jens Neuse <jens.neuse@gmx.de>
=> feat: planner, support custom scalar fields (#450)

pkg/ast/ast_node_kind.go, pkg/ast/ast_node_kind_test.go, pkg/astvisitor/visitor.go, pkg/engine/datasource/graphql_datasource/graphql_datasource.go, pkg/engine/datasource/graphql_datasource/graphql_datasource_test.go, pkg/engine/datasource/graphql_datasource/graphql_sse_handler.go, pkg/engine/datasource/graphql_datasource/graphql_sse_handler_test.go, pkg/engine/datasource/graphql_datasource/graphql_subscription_client.go, pkg/engine/plan/plan.go, pkg/graphql/execution_engine_v2_test.go
This PR contains following PRs:
- https://github.com/wundergraph/graphql-go-tools/pull/487
- https://github.com/wundergraph/graphql-go-tools/pull/486
- https://github.com/wundergraph/graphql-go-tools/pull/477
=> cherry-pick wundergraph changes

pkg/graphql/execution_engine_test.go, pkg/graphql/execution_engine_v2_test.go
Added an additional test case for nested field-mapping for increasing confidence.
=> add test case for nested field mappings

pkg/asyncapi/asyncapi.go, pkg/asyncapi/asyncapi_test.go, pkg/asyncapi/converter.go
This PR includes a few improvements for [TT-7684](https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/26?modal=detail&selectedIssue=TT-7684).
[TT-7684]: https://tyktech.atlassian.net/browse/TT-7684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TT-7684] UDG datasource config based on info parsed from AsyncAPI spec

pkg/ast/ast_argument.go, pkg/ast/ast_directive.go, pkg/ast/ast_directive_definition.go, pkg/ast/ast_fragment_definition.go, pkg/astparser/parser.go, pkg/astprinter/astprinter.go, pkg/astprinter/astprinter_test.go, pkg/astvalidation/definition_validation.go, pkg/astvalidation/operation_rule_directives_unique_per_location.go, pkg/astvalidation/reference/testsgo/UniqueDirectivesPerLocationRule_test.go, pkg/astvalidation/reference/testsgo/harness_test.go, pkg/astvalidation/rule_known_type_names.go, pkg/astvisitor/simplevisitor.go, pkg/astvisitor/visitor.go, pkg/engine/resolve/resolve.go, pkg/engine/resolve/resolve_test.go, pkg/execution/planning_test.go, pkg/federation/sdlmerge/sdlmerge_test.go, pkg/federation/sdlmerge/testdata/validate-subgraph/lack-definition-non-null.graphqls, pkg/federation/sdlmerge/testdata/validate-subgraph/lack-definition.graphqls, pkg/federation/sdlmerge/testdata/validate-subgraph/lack-extend-definition-non-null.graphqls, pkg/federation/sdlmerge/testdata/validate-subgraph/lack-extend-definition.graphqls, pkg/federation/sdlmerge/testdata/validate-subgraph/well-defined-non-null.graphqls, pkg/federation/sdlmerge/testdata/validate-subgraph/well-defined.graphqls, pkg/lexer/literal/literal.go, pkg/operationreport/externalerror.go, pkg/testing/federationtesting/products/graph/schema.resolvers.go
This PR contains changes from WG, including:
- https://github.com/wundergraph/graphql-go-tools/pull/503
- https://github.com/wundergraph/graphql-go-tools/pull/504
- https://github.com/wundergraph/graphql-go-tools/pull/514
- https://github.com/wundergraph/graphql-go-tools/pull/515
=> cherry-pick wg changes

pkg/openapi/openapi.go
This PR includes preliminary work for [TT-7767](https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/26?modal=detail&selectedIssue=TT-7767). 
* Added a new public method to parse the OpenAPI document only one time: `ParseOpenAPIDocument`
* Make some private functions public to reuse them in GW: `MakeInputTypeName`, `MakeFieldNameFromOperationID`, `MakeFieldNameFromEndpoint`, `MakeParameterName`.
[TT-7767]: https://tyktech.atlassian.net/browse/TT-7767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TT-7767] UDG datasource config based on info parsed from OAS spec

pkg/variablevalidator/variablevalidator.go, pkg/variablevalidator/variablevalidator_test.go
handle unsanitized json in variables
=> [TT-8944]: Fix: handle unsanitized json in variables

pkg/http/ws.go, pkg/subscription/context.go, pkg/subscription/context_test.go, pkg/subscription/handler.go, pkg/subscription/handler_test.go, pkg/subscription/init.go, pkg/subscription/mock_client_test.go
- sync wg commit: https://github.com/wundergraph/graphql-go-tools/pull/406
=> add ws init func (TT-9257)

pkg/subscription/engine.go, pkg/subscription/handler.go, pkg/subscription/websocket/handler_test.go
This PR adds a missing error handling for OnbeforeStart hooks.
=> add OnBeforeStartHook error handling

pkg/subscription/websocket/protocol_graphql_transport_ws.go, pkg/subscription/websocket/protocol_graphql_transport_ws_test.go, pkg/subscription/websocket/protocol_graphql_ws.go, pkg/subscription/websocket/protocol_graphql_ws_test.go
this PR fixes a panic on broken subscription input
=> fix panic on broken subscription input

pkg/subscription/websocket/protocol_graphql_transport_ws.go, pkg/subscription/websocket/protocol_graphql_transport_ws_test.go
This PR allows `pong` as birectional message.
=> allow pong as bidirectional message

pkg/subscription/engine.go, pkg/subscription/engine_test.go
This PR fixes an issue where not all subscriber ids where checked for duplication.
=> always check for duplicate subscriber ids

pkg/variablevalidator/variablevalidator.go, pkg/variablevalidator/variablevalidator_test.go
This PR makes changes to the VariableValidation package and supports nested errors as well as validationErrors that make use of $defs and $refs. It also refactors the format of error messages.
[TT-8710](https://tyktech.atlassian.net/browse/TT-8710)
[TT-8710]: https://tyktech.atlassian.net/browse/TT-8710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TT-8710]: refactor: better error messages from variable validation

pkg/graphql/execution_engine_v2.go, pkg/graphql/execution_engine_v2_test.go, pkg/postprocess/fetchinput.go, pkg/postprocess/injectheader_test.go, pkg/postprocess/modifyheader.go, pkg/postprocess/modifyheader_test.go, pkg/postprocess/postprocess.go, pkg/subscription/executor_v2.go
This PR adds a header modifier post processor.
=> add header modifier post processor

pkg/subscription/engine_test.go, pkg/subscription/handler_test.go, pkg/subscription/time_out_test.go, pkg/subscription/websocket/client.go, pkg/subscription/websocket/client_test.go, pkg/subscription/websocket/protocol_graphql_transport_ws_test.go
This PRs removes some race conditions and optimizes subscription tests
=> optimize subscription tests

pkg/subscription/constants.go, pkg/subscription/engine.go, pkg/subscription/engine_test.go, pkg/subscription/handler.go, pkg/subscription/websocket/handler.go
[TT-9882](https://tyktech.atlassian.net/browse/TT-9882)
[TT-9882]: https://tyktech.atlassian.net/browse/TT-9882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TT-9882]: added an exponential backoff to the subscription retry in case of a dead connection

pkg/subscription/engine.go
[TT-9882](https://tyktech.atlassian.net/browse/TT-9882)
[TT-9882]: https://tyktech.atlassian.net/browse/TT-9882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TT-9882]: fix typo with subscription error

pkg/graphql/extractor.go, pkg/graphql/extractor_test.go
[TT-9467](https://tyktech.atlassian.net/browse/TT-9476)
[TT-9467]: https://tyktech.atlassian.net/browse/TT-9467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TT-9467]: added limit for operation in graphql extractor

pkg/engine/datasource/kafka_datasource/kafka_datasource_test.go, pkg/engine/datasource/kafka_datasource/testdata/kafka_jaas.conf
Remove leftover test data and useless `defer` calls.
=> [TT-10375] Cleanup

pkg/openapi/fixtures/v3.0.0/unnamed-object.graphql, pkg/openapi/fixtures/v3.0.0/unnamed-object.yaml, pkg/openapi/openapi.go, pkg/openapi/openapi_test.go, v2/pkg/openapi/fixtures/v3.0.0/unnamed-object.graphql, v2/pkg/openapi/fixtures/v3.0.0/unnamed-object.yaml, v2/pkg/openapi/openapi.go, v2/pkg/openapi/openapi_test.go
PR for [TT-10565](https://tyktech.atlassian.net/browse/TT-10565)
[TT-10565]: https://tyktech.atlassian.net/browse/TT-10565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TT-10565] Handle unnamed object definitions in OpenAPI documents

pkg/openapi/fixtures/v3.0.0/tt-10696-unnamed-array-of-objects.graphql, pkg/openapi/fixtures/v3.0.0/tt-10696-unnamed-array-of-objects.yaml, pkg/openapi/fixtures/v3.0.0/tt-10696-unnamed-array-of-primitive-types.graphql, pkg/openapi/fixtures/v3.0.0/tt-10696-unnamed-array-of-primitive-types.yaml, pkg/openapi/fixtures/v3.0.0/tt-10696-unnamed-object.graphql, pkg/openapi/fixtures/v3.0.0/tt-10696-unnamed-object.yaml, pkg/openapi/fixtures/v3.0.0/tt-10696.graphql, pkg/openapi/fixtures/v3.0.0/tt-10696.yaml, pkg/openapi/openapi.go, pkg/openapi/openapi_test.go, pkg/openapi/utils.go, v2/pkg/openapi/fixtures/v3.0.0/tt-10696-unnamed-array-of-objects.graphql, v2/pkg/openapi/fixtures/v3.0.0/tt-10696-unnamed-array-of-objects.yaml, v2/pkg/openapi/fixtures/v3.0.0/tt-10696-unnamed-array-of-primitive-types.graphql, v2/pkg/openapi/fixtures/v3.0.0/tt-10696-unnamed-array-of-primitive-types.yaml, v2/pkg/openapi/fixtures/v3.0.0/tt-10696-unnamed-object.graphql, v2/pkg/openapi/fixtures/v3.0.0/tt-10696-unnamed-object.yaml, v2/pkg/openapi/fixtures/v3.0.0/tt-10696.graphql, v2/pkg/openapi/fixtures/v3.0.0/tt-10696.yaml, v2/pkg/openapi/openapi.go, v2/pkg/openapi/openapi_test.go, v2/pkg/openapi/utils.go
PR for [TT-10696](https://tyktech.atlassian.net/browse/TT-10696). 
[TT-10696]: https://tyktech.atlassian.net/browse/TT-10696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TT-10696] Handling of objects that do not have any properties

pkg/graphql/request.go, pkg/graphql/request_test.go, pkg/graphql/validation.go, pkg/graphql/validation_test.go
In this PR we're modifying IsValidate to check validation using the validForSchema attribute
=> Modify IsValidated 

pkg/graphql/request.go, pkg/graphql/request_test.go
refactoring work and adding testing from this PR 
https://github.com/TykTechnologies/graphql-go-tools/pull/413
=> Add testing is validated

go.mod, go.sum, pkg/engine/datasource/httpclient/httpclient_test.go, pkg/engine/datasource/httpclient/nethttpclient.go, pkg/graphql/execution_engine_v2.go, pkg/graphql/execution_engine_v2_test.go, v2/go.mod, v2/go.sum, v2/pkg/engine/datasource/httpclient/httpclient_test.go, v2/pkg/engine/datasource/httpclient/nethttpclient.go, v2/pkg/graphql/execution_engine_v2.go, v2/pkg/graphql/execution_engine_v2_test.go
This PR adds brotli encoding/decoding support
=> add brotli support

v2/pkg/openapi/fixtures/v3.0.0/status-code-precedence.graphql, v2/pkg/openapi/fixtures/v3.0.0/status-code-precedence.yaml, v2/pkg/openapi/fixtures/v3.0.0/status-code-valid-responses.graphql, v2/pkg/openapi/fixtures/v3.0.0/status-code-valid-responses.yaml, v2/pkg/openapi/fulltype.go, v2/pkg/openapi/mutation.go, v2/pkg/openapi/openapi_test.go, v2/pkg/openapi/query.go, v2/pkg/openapi/utils.go, v2/pkg/openapi/utils_test.go
See https://github.com/TykTechnologies/graphql-go-tools/pull/423 for details.
=> [TT-11249] Copy changes to v2 folder

go.mod, go.sum, pkg/engine/datasource/graphql_datasource/graphql_subscription_client.go, pkg/engine/datasource/graphql_datasource/graphql_subscription_client_test.go, pkg/engine/datasource/graphql_datasource/graphql_tws_handler.go, pkg/engine/datasource/graphql_datasource/graphql_tws_handler_test.go, pkg/engine/datasource/graphql_datasource/graphql_ws_handler.go, pkg/engine/datasource/graphql_datasource/graphql_ws_handler_test.go, v2/go.mod, v2/go.sum, v2/pkg/engine/datasource/graphql_datasource/graphql_subscription_client.go, v2/pkg/engine/datasource/graphql_datasource/graphql_subscription_client_test.go, v2/pkg/engine/datasource/graphql_datasource/graphql_tws_handler.go, v2/pkg/engine/datasource/graphql_datasource/graphql_tws_handler_test.go, v2/pkg/engine/datasource/graphql_datasource/graphql_ws_handler.go, v2/pkg/engine/datasource/graphql_datasource/graphql_ws_handler_test.go
nhooyr.io/websocket has changed to github.com/coder/websocket and this can cause dependency issues.
=> change nhooyr.io/websocket to github.com/coder/websocket

pkg/engine/datasource/kafka_datasource/kafka_consumer_group.go, pkg/engine/datasource/kafka_datasource/kafka_datasource_test.go, pkg/engine/resolve/resolve_test.go
[TT-13924](https://tyktech.atlassian.net/browse/TT-13924)
[TT-13924]: https://tyktech.atlassian.net/browse/TT-13924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TT-13924]: fix issue where kafka datasource expects data

pkg/graphql/input_validation_test.go, pkg/graphql/schema.go, pkg/graphql/schema_test.go
[TT-14582](https://tyktech.atlassian.net/browse/TT-14582)
[TT-14582]: https://tyktech.atlassian.net/browse/TT-14582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TT-14582]: Fix issue with arguments not being extracted for interfaces
