TykTechnologies/graphql-go-tools

- .github/workflows/main.yml
As for now, only the latest go version is used in the pipeline.
This situation could lead to incompatibilities between tyk and graphql-go-tools, so I have added a build matrix which will test at least against tyk's go version, and the latest go version.
It will also run on all defined OS, currently `ubuntu-latest` and `macos-latest`. `windows-latest` could also be added, but this would require much more work because the pipeline currently relies on makefiles and bash scripts.
> Enable matrix testing for CI

- pkg/graphql/execution_engine.go
- pkg/graphql/execution_engine_test.go
Let's give a helper function to user to convert the buffer to HTTP response. We give http request as parameter, most user will expect http response and will get by just this: `executionResult.GetAsHTTPResponse()`. 
If they want to read the result, they will be able to use `executionResult.Buffer()` and they will read how they want.
Usage on the  Gateway side: 
```
result, err = p.TykAPISpec.GraphQLExecutor.Engine.Execute(context.Background(), gqlRequest, graphql.ExecutionOptions{ExtraArguments: nil})
res = result.GetAsHTTPResponse()
```
> Return ExecutionResult object from Execute

- pkg/execution/datasource/datasource_http_json.go
- pkg/execution/datasource_http_json_test.go
- pkg/execution/execution_test.go
This PR will ensure that setting the default typename works for arrays as the root type too.
> Fix setting default typename on array response

- pkg/ast/ast_operation_definition.go
On CPU architectures, where data units are less than 64bit wide builds currently fail with an overflow. This is due to implicit type in the for loop iterator `i` in `Document.GenerateUnusedVariableDefinitionName` function, which the compiler guesses as just `int`. This type is architecture dependent, so that on 32bit arch it's an `int32`, while on 64bit one it's an `int64`.
When setting the loop's upper bound at `math.MaxInt64` and trying to compile it with `GOARCH=386` variable `i` would be of `int32` type and thus cause an overflow (which is detected by the compiler). This change makes loop iterator types explicit as `int64`.
> Fixes build for less than 64bit architectures

- pkg/playground/playground.go
`path.Join` doesn't respect trailing `/`, so we need to make manual check and concatenate it at the end of playground url.
> Respect trailing slashes during playground url concatenation

- pkg/escape/bytes.go
- pkg/escape/bytes_test.go
- pkg/execution/datasource/datasource_http_json.go
- pkg/execution/execution.go
- pkg/execution/execution_test.go
- pkg/execution/jsonvaluetype.go
Essentially it is an additional set of fixes, for the previous PR https://github.com/TykTechnologies/graphql-go-tools/pull/61
Quoting and Unquoting is not that straightforward, take a loot at https://golang.org/src/encoding/json/decode.go `unquoteBytes` function. 
We continue hitting bugs related to escaped symbols, because built-in "escape" function does not handle some cases. And based on the implementation I see in Golang there are way more. 
This PR makes it use standard `strconv.Quote` function, which handles all these scenarios. 
Additionally, I was not able to figure out what this lines do (and frankly the logic itself is a bit off), so I just removed them:
https://github.com/TykTechnologies/graphql-go-tools/pull/66/files#diff-b07a4e25e3d7f6482ed988bdf67cbfe8L280-L281
Plus in some …
> Fix nested escaping of `\` escape symbol

- pkg/ast/ast_operation_definition.go
- pkg/ast/ast_operation_definition_test.go
- pkg/engine/plan/plan.go
- pkg/engine/plan/plan_test.go
From GraphQL Spec:
```
GetOperation(document, operationName)
- If operationName is null:
- If document contains exactly one operation.
- Return the Operation contained in the document.
- Otherwise produce a query error requiring operationName.
Otherwise:
- Let operation be the Operation named operationName in document.
- If operation was not found, produce a query error.
- Return operation.
```
> fix operation name regression (TT-687)

- .github/workflows/main.yml
- go.mod
- go.sum
- pkg/engine/datasource/httpclient/compatibility_1.12.go
- pkg/engine/datasource/httpclient/nethttpclient.go
- pkg/engine/resolve/resolve.go
Changed CI pipeline to min version go 1.12 and remove the in-between versions 1.13 and 1.14.
> add compatibility for go 1.12 (TT-687)

- pkg/engine/resolve/resolve.go
- pkg/engine/resolve/resolve_mock_test.go
- pkg/engine/resolve/resolve_test.go
- pkg/graphql/execution_engine_v2_test.go
This PR adds a hook context to the execution hooks.
The hook ctx contains the current path of the execution, helping the caller to understand where in the execution the hook triggered.
> implement hook context with path

- pkg/engine/datasource/rest_datasource/rest_datasource_test.go
- pkg/engine/plan/plan.go
- pkg/graphql/execution_engine_v2_test.go
argument templates like `{{.arguments.id}}` were not working because the only accepted template needed spaces until now (e.g. `{{ .arguments.id }}`)
> fix arguments not resolving correctly

- pkg/engine/datasource/graphql_datasource/graphql_datasource_test.go
- pkg/engine/datasource/rest_datasource/rest_datasource_test.go
- pkg/engine/plan/plan.go
- pkg/graphql/execution_engine_v2_test.go
This PR will enforce dot as the first non-space character in templates.
Currently it is possible to use `{{ .request.headers.XXX }}` as well as `{{ request.headers.XXX }}`
It will also change `{{ .request.header.XXX }}` to `{{ .request.headers.XXX }}`
> enforce dot as first non-space character in templates (TT-1769)

- pkg/engine/datasource/graphql_datasource/graphql_datasource.go
- pkg/engine/datasource/graphql_datasource/graphql_datasource_test.go
- pkg/engine/datasource/rest_datasource/rest_datasource.go
- pkg/engine/datasource/rest_datasource/rest_datasource_test.go
- pkg/engine/datasource/staticdatasource/static_datasource.go
- pkg/engine/datasourcetesting/datasourcetesting.go
- pkg/engine/plan/plan.go
This PR will fix a problem, where it wasn't possible to execute an aliased field data source when this data source was already invoked with the same field.
This resulted in a problem, where REST Data Source could only be used once.
Example:
```
{
hello(name = "world")
anotherHello: hell(name = "max")
}
```
This would result in invoking the `Query.hello` data source only once.
> fix unable to reuse an aliased field data sources (TT-538)

- pkg/ast/ast_object_type_extension.go
- pkg/astnormalization/astnormalization.go
- pkg/astnormalization/astnormalization_test.go
- pkg/astnormalization/definition_normalization.go
- pkg/astnormalization/definition_normalization_test.go
- pkg/astnormalization/object_type_extending_test.go
move definition normalization to a separate type
add WithNormalizeDefinition option for OperationNormalizer
include interfaces when extending object type definition
> Add separate definition normalizer

- pkg/astvalidation/astvalidation.go
- pkg/astvalidation/astvalidation_test.go
This PR fixes a problem where validation failed when using inline fragments for a federation schema
> fix _entities queries validation for federation schemas

- pkg/ast/ast_node.go
- pkg/ast/ast_object_type_extension.go
- pkg/astnormalization/implicit_extend_root_operation.go
- pkg/astnormalization/subgraph_sdl_normalization.go
- pkg/astnormalization/subgraph_sdl_normalization_test.go
- pkg/federation/sdlmerge/sdlmerge.go
- pkg/federation/sdlmerge/sdlmerge_test.go
An elaborate description can be found here https://tyktech.atlassian.net/browse/TT-2669
before running any visitors of `sdlmerge`, we run a helper that modifies ObjectTypeDefinition with fields to be ObjectTypeExtension
> TT-2669 explicit extend keyword on subgraph major object type

- go.mod
- pkg/engine/datasource/graphql_datasource/graphql_subscription_client.go
- pkg/engine/datasource/graphql_datasource/graphql_subscription_client_test.go
This is a temporary "fix" to disable deduplication which does not work with the current state of the planner.
> disable websocket deduplication

- pkg/ast/ast_selection.go
- pkg/astparser/errors.go
- pkg/astparser/parser.go
- pkg/astparser/parser_test.go
- pkg/astparser/parser_token_helpers.go
- pkg/astparser/tokenizer.go
- pkg/astprinter/astprinter.go
- pkg/astprinter/astprinter_test.go
Benchmark results:
On master:
```
goos: darwin
goarch: arm64
pkg: github.com/jensneuse/graphql-go-tools/pkg/astparser
BenchmarkParseStarwars
BenchmarkParseStarwars-8        	   22077	     47744 ns/op	 237.24 MB/s	    1210 B/op	      37 allocs/op
BenchmarkParseGithub
BenchmarkParseGithub-8          	     511	   2349871 ns/op	 250.10 MB/s	   84210 B/op	     971 allocs/op
BenchmarkSelectionSet
BenchmarkSelectionSet-8         	  991680	      1157 ns/op	 234.30 MB/s	       0 B/op	       0 allocs/op
BenchmarkIntrospectionQuery
BenchmarkIntrospectionQuery-8   	  205233	      5857 ns/op	 222.64 MB/s	       0 B/op	       0 allocs/op
BenchmarkKitchenSink
BenchmarkKitchenSink-8          	  247881	      4865 ns/op	 209.67 MB/s	       0 B/op	       0 allocs/op
BenchmarkParse
BenchmarkParse-8 …
```
> add support of comments everywhere

- pkg/astvalidation/rule_implement_transitive_interfaces.go
- pkg/astvalidation/rule_implement_transitive_interfaces_test.go
- pkg/operationreport/externalerror.go
This PR adds new test cases for validating transitive interfaces and interface extensions. Basically, I added a new control block to `EnterInterfaceTypeExtension`. If the interface extension has no fields, it adds an error to the report.
Related issue on Jira: [TT-4535](https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/26?modal=detail&selectedIssue=TT-4535)
> add test cases to existing functionality (TT-4535)

- pkg/astvalidation/definition_validation.go
- pkg/astvalidation/rule_implementing_types_are_supersets.go
- pkg/astvalidation/rule_implementing_types_are_supersets_test.go
- pkg/operationreport/externalerror.go
This PR adds a validation rule that checks if all types that implement an interface are supersets of the interfaces.
> add rule for implementing types are supersets (TT-4486)

- pkg/playground/files/playground.html
PR for [TT-4588](https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/26?modal=detail&selectedIssue=TT-4588)
This bug is spotted on SonarCloud. Here is the explanation:
> **Add "lang" and/or "xml:lang" attributes to this "<html>" element**
>
> The <html> element should provide the lang and/or xml:lang attribute in order to identify the default language of a document.
> 
> It enables assistive technologies, such as screen readers, to provide a comfortable reading experience by adapting the pronunciation and accent to the language. It also helps braille translation software, telling it to switch the control codes for accented characters for instance.
> 
> Other benefits of marking the language include:
> 
> assisting user agents in providing dictionary definitions or helping …
> Testing on graphql-go-tools repository (TT-4588)

- pkg/engine/datasource/graphql_datasource/graphql_datasource.go
- pkg/engine/datasource/graphql_datasource/graphql_datasource_test.go
PR for [TT-4625](https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/26?modal=detail&selectedIssue=TT-4625)
There was a minor mistake in the test. `type` field in the JSON schema is an array of strings, not a string. See this: 114dfdc6ca26bd7844ac110f7aaf55137e7c3ddd
> Avoid printing the same variable twice for a query (TT-4625)

- pkg/ast/ast_node.go
- pkg/astnormalization/fragment_spread_inlining.go
- pkg/astnormalization/fragment_spread_inlining_test.go
- pkg/astvalidation/operation_validation_test.go
```
When expanding a named fragment, one of the cases to consider is that
the named fragment has union type, but the enclosing type is an
interface type.  (e.g. `user { ...data } fragment data on SomeUnion {...}`,
where `user` has an interface type.  fragment_spread_inlining.go already
treats this case correctly.
However, there's a symmetrical case where the enclosing type is a
union, and the naamed fragment has an interface type.  According to
the spec, this should be treated identically, but
fragment_spread_inlining.go was not considering this case.  With this
PR it is.
Fixing this turned up another problem in ast_node.go:
NodeFragmentIsAllowedOnInterfaceTypeDefinition properly allowed the
fragment on union types when appropriate, but in the symmetrical case, …
```
> treat a union intersecting an interface symmetrically from interface | union

- pkg/engine/datasource/kafka_datasource/kafka_consumer_group.go
- pkg/engine/datasource/kafka_datasource/kafka_consumer_group_test.go
- pkg/engine/datasource/kafka_datasource/kafka_datasource.go
This PR([TT-4369](https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/26?selectedIssue=TT-4369)) implements the Kafka consumer group. It's an internal part of the Kafka data source. Basically, it starts a new consumer with the given config and it maintains the consumer during the subscription's life cycle. 
The data source implementation will use `Subscribe` function to subscribe to a topic with the given config. If the consumer quits in any way, it will close the `next` channel. I extracted the flow from `WebSocketGraphQLSubscriptionClient`. Please note that it implements `graphql-ws` protocol to communicate with the other GraphQL services. We don't need this with Kafka. 
graphql-ws: https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md
Here is the initial version …
> [TT-4369] Kafka Consumer Group implementation

- pkg/federation/sdlmerge/remove_scalar_duplicates.go
- pkg/federation/sdlmerge/sdlmerge.go
- pkg/federation/sdlmerge/sdlmerge_test.go
[changelog]
internal: Duplicated scalars among merged schemas will be removed so only one of that scalar name will exist within the federated schema.
> [TT 4815] Remove duplicated scalars from federated schemas

- pkg/engine/datasource/introspection_datasource/input.go
- pkg/engine/datasource/introspection_datasource/input_test.go
- pkg/engine/datasource/introspection_datasource/planner_test.go
- pkg/engine/resolve/inputtemplate.go
- pkg/engine/resolve/variable.go
- pkg/graphql/execution_engine_v2_test.go
This PR fixes the object rendering for strings in the `PlainVariableRenderer`.
It will now remember a string after parsing it so that Quotes will be removed afterward. This change also required a change in the introspection data source.
> fix broken object variable rendering when handling strings

- pkg/engine/datasource/kafka_datasource/kafka_consumer_group.go
- pkg/engine/datasource/kafka_datasource/kafka_consumer_group_test.go
- pkg/engine/datasource/kafka_datasource/kafka_datasource.go
- pkg/engine/datasource/kafka_datasource/kafka_datasource_test.go
Here is the PR for [TT-5192](https://tyktech.atlassian.net/browse/TT-5192).
I added a new configuration option to start consuming from the latest offset after a client restart. Here is the basic flow:
* Set `sarama.OffsetNewest` to `sarama.Config.Consumer.Offsets.Initial`.
* Reset the offset before starting to consume. 
* Do not commit the current offset when consuming a new message.
Unfortunately, it's not possible to test this improvement via `sarama.MockBroker`. I assume that Sarama implements `ResetOffset` correctly and Kafka process that command without any flaw, and I decided to implement tests by observing the behavior of our business logic. Basically, I provided mock implementations of `sarama.ConsumerGroupClaim` and `sarama.ConsumerGroupSession` interfaces to observe the effects …
> [TT-5192] Kafka - allow user to configure which messages are the first to read

- pkg/engine/datasource/rest_datasource/rest_datasource_test.go
- pkg/engine/plan/plan.go
- pkg/engine/resolve/variable.go
- pkg/graphql/execution_engine_v2_test.go
- pkg/graphqljsonschema/jsonschema.go
- pkg/graphqljsonschema/jsonschema_test.go
This PR is based on https://github.com/TykTechnologies/graphql-go-tools/pull/221 from @buraksezer 
It fixes the issue of not being able to access nested fields on context variables (including json schema validation):
`{{.object.pet.name}}`
> fix accessing nested fields on context variables

- examples/kafka_pubsub/transactional_producer/README.md
- examples/kafka_pubsub/transactional_producer/go.mod
- examples/kafka_pubsub/transactional_producer/go.sum
- examples/kafka_pubsub/transactional_producer/main.go
This PR adds a test tool for transactional producer API. 
Unfortunately, [shopify/sarama](https://github.com/Shopify/sarama) and [segment-io/kafka](https://github.com/segmentio/kafka-go) don't support transactional producer API. Because of that, we need to use [confluentinc/confluent-kafka-go/kafka](https://github.com/confluentinc/confluent-kafka-go/kafka).
We don't need to update the library commit hash in Tyk gateway and its siblings. This PR only includes a test tool.
> [TT-5328] Add a test tool for transactional producer API

- pkg/engine/datasource/graphql_datasource/graphql_subscription_client.go
- pkg/engine/datasource/graphql_datasource/graphql_subscription_client_test.go
This PR adds a loop that waits for a connection ack while accepting ka as per [here](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md). Any other response before the connection has been initialised is taken as an error.
> subscription: add support for ka while waiting for ack

- examples/kafka_pubsub/README.md
- examples/kafka_pubsub/docker-compose-cluster.yml
- examples/kafka_pubsub/main.go
- pkg/engine/datasource/kafka_datasource/config.go
- pkg/engine/datasource/kafka_datasource/config_test.go
- pkg/engine/datasource/kafka_datasource/kafka_consumer_group.go
- pkg/engine/datasource/kafka_datasource/kafka_consumer_group_test.go
- pkg/engine/datasource/kafka_datasource/kafka_datasource_test.go
- pkg/engine/datasource/kafka_datasource/sarama_config_parameters_test.go
We now support multiple broker addresses in the Kafka data source. The integration test suite was modified to support Kafka clusters instead of a standalone broker. Now it's easy to create a Kafka cluster with a few lines of code:
```go
k := newKafkaCluster(t)
brokers := k.start(t, 3)
```
This simple snippet creates a Kafka cluster with three nodes.  See `pkg/engine/datasource/kafka_datasource/sarama_config_parameters_test.go` file for details. 
I also updated the documentation. See **Creating an Apache Kafka cluster** section in `examples/kafka_pubsub/README.md` file
> [TT-5115] Implement multiple broker adds config in Sarama

- examples/kafka_pubsub/README.md
- examples/kafka_pubsub/transactional_producer/README.md
- examples/kafka_pubsub/tyk-api-definition.json
- pkg/engine/datasource/kafka_datasource/config_test.go
- pkg/engine/datasource/kafka_datasource/kafka_datasource_test.go
I have updated the documents to cover multiple broker addresses improvement. This PR doesn't require a library update in Tyk and its siblings.
> [TT-5115] Improve Kafka data source documents

- pkg/graphql/request.go
This PR fixes [TT-5704](https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/26?modal=detail&selectedIssue=TT-5704).
Basically, my fix prevents marking a query as parsed unless it is parsed successfully. Now every caller of `parseQueryOnce` can be aware of parsing errors.
> [TT-5704] Gateway crashing when running a wrongly written subscription with WSS in Postman

- examples/kafka_pubsub/README.md
- examples/kafka_pubsub/tyk-api-definition.json
- pkg/engine/datasource/kafka_datasource/config.go
- pkg/engine/datasource/kafka_datasource/config_test.go
- pkg/engine/datasource/kafka_datasource/kafka_consumer_group.go
- pkg/engine/datasource/kafka_datasource/kafka_consumer_group_test.go
- pkg/engine/datasource/kafka_datasource/kafka_datasource.go
- pkg/engine/datasource/kafka_datasource/kafka_datasource_test.go
- pkg/engine/datasource/kafka_datasource/sarama_config_parameters_test.go
With this PR, the Kafka data source can subscribe to multiple topics on a Kafka cluster. See `TestSarama_Subscribe_To_Multiple_Topics` for details.
I also improved the test suite for the sake of maintainability.
> [TT-6022] Kafka data source should subscribe to multiple topics

- pkg/graphql/execution_engine_v2.go
- pkg/postprocess/injectheader.go
- pkg/postprocess/injectheader_test.go
- pkg/postprocess/postprocess.go
This Pr adds a new post processor that allows manipulation of the headers for requests being sent to upstream.
[TT-5852](https://tyktech.atlassian.net/browse/TT-5852)
> engine: added support for injected header

- pkg/graphql/request_fields_validator.go
- pkg/graphql/request_fields_validator_test.go
PR for [TT-6110](https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/26?modal=detail&selectedIssue=TT-6110)
Initially, I thought it was good to use an empty fields list to implement that feature but the current implementation validates the input if the fields list is empty. So in order to avoid breaking the API and its behavior, I decided to use an asterisk(*) character to denote all fields of a type are allowed or blocked. 
See the following snippets:
```go
FieldRestrictionList{
Kind: AllowList,
Types: []Type{
{
Name:   "Query",
Fields: []string{"hero"},
},
{
Name:   "Character",
Fields: []string{"*"},
},
},
}
```
The above sample allows all fields of the `Character` type.
```go
FieldRestrictionList{
Kind: BlockList,
Types: []Type{
{
Name:   "Character",
Fields: …
```
> [TT-6110] Allow list for field based permissions implement allow block full types with asterisk

- pkg/astnormalization/input_coercion_for_list.go
- pkg/astnormalization/input_coercion_for_list_test.go
Fixed a bug where an extra value in the input (in variables) passed would cause the input_coercion_for_list visitor to panic
[TT-6552](https://tyktech.atlassian.net/browse/TT-6552)
> [TT-6552] fixed bug in input coercion for list when extra invalid input passed

- pkg/graphql/request_fields_validator.go
- pkg/graphql/request_fields_validator_test.go
This PR fixes the bug described here: https://tyktech.atlassian.net/browse/TT-6110?focusedCommentId=28231
The bug is caused by the mislocation of the asterisk check and iterating over a map. Now it checks the asterisk character first for a requested type, then tries to find a disallowed field if there is any.
Also, I would like to clarify the usage of this allow-list feature. The following config snippet allows to access all current and future fields of the `Query` type.  But the other types and their fields are still disallowed to access. So the asterisk operator doesn't work recursively.
```json
"allowed_types": [
{
"name": "Query",
"fields": ["*"]
}
]
```
The following configuration snippet allows to access all current and future fields of the `Query` type. It also allows to access the …
> [TT-6110] Fix inconsistent behavior of the asterisk operator

- pkg/graphql/request.go
- pkg/graphql/request_test.go
This PR proposes a solution for the problem described here: [TT-6669](https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/26?modal=detail&selectedIssue=TT-6669)
After an initial investigation, I found that the original author deliberately implemented the feature I described in the ticket. 
In brief, the following query is an introspection query:
```graphql
{
__schema {
types {
name
}
}
}
```
`IsIntrospectionQuery` returns true for this and this is the expected behavior. But if we add an additional field to the above query, `IsIntrospectionQuery` returns false and this behavior breaks the granular access policy of Tyk Gateway. See the related ticket on Jira: [TT-6568](https://tyktech.atlassian.net/browse/TT-6568)
```graphql
{
__schema {
types {
name
}
}
countries { name }
} …
```
> [TT-6669] Strict version of IsIntrospectionQuery

- go.mod
- go.sum
- pkg/engine/datasource/graphql_datasource/graphql_datasource.go
- pkg/engine/datasource/graphql_datasource/graphql_datasource_test.go
- pkg/engine/datasource/graphql_datasource/graphql_sse_handler.go
- pkg/engine/datasource/graphql_datasource/graphql_sse_handler_test.go
- pkg/engine/datasource/graphql_datasource/graphql_subscription_client.go
- pkg/engine/datasource/graphql_datasource/graphql_subscription_client_test.go
- pkg/engine/datasource/graphql_datasource/graphql_tws_handler.go
- pkg/engine/datasource/graphql_datasource/graphql_tws_handler_test.go
- pkg/engine/datasource/graphql_datasource/graphql_ws_handler.go
- pkg/engine/datasource/graphql_datasource/graphql_ws_handler_test.go
- pkg/engine/datasource/graphql_datasource/graphql_ws_proto_types.go
- pkg/engine/datasource/httpclient/httpclient.go
This PR ports the new subscription protocol implementations (SSE, graphql-transport-ws) from Wundergraph to Tyk.
> add new subscription protocols from wg

- pkg/engine/datasource/graphql_datasource/graphql_sse_handler_test.go
- pkg/engine/datasource/graphql_datasource/graphql_tws_handler.go
- pkg/engine/datasource/graphql_datasource/graphql_tws_handler_test.go
- pkg/engine/datasource/graphql_datasource/graphql_ws_handler.go
- pkg/engine/datasource/graphql_datasource/graphql_ws_handler_test.go
- pkg/engine/datasource/graphql_datasource/graphql_ws_proto_types.go
This PR fixes the wrong handling of connection errors in the GQL subscription. Previously, it was hiding the connection errors due to this faulty behavior, it was failing to trigger the reconnection mechanism. It was waiting forever in an uninterruptible and unobservable state. 
I added integration tests to simulate an upstream failure. Basically, the tests kill the underlying TCP socket and trigger the reconnection mechanism, and return the error messages.
For example, if I kill the upstream service at some point it returns the following error messages:
```json
{"id":"1","type":"data","payload":{"errors":[{"message":"unable to resolve","locations":[{"line":2,"column":3}],"path":["getUserNotifications"]},{"message":"failed to get reader: failed to read frame header: EOF"}],"data":null}} …
```
> [TT-6798] Reconnection feature is broken in subscription

- pkg/engine/resolve/resolve.go
- pkg/engine/resolve/resolve_test.go
PR for [TT-6737](https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/26?modal=detail&selectedIssue=TT-6737)
Now the library returns the following error if the data source has not been defined: 
```json
{"errors":[{"message":"no data source found"}]}
```
I investigated the possibility of controlling this before calling `ResolveGraphQLSubscription` but it seems that there is no way to do it. See the following: 
```go
func (v *Visitor) LeaveDocument(operation, definition *ast.Document) {
for _, config := range v.fetchConfigurations {
if config.isSubscription {
v.configureSubscription(config)
} else {
v.configureObjectFetch(config)
}
}
}
```
`v.fetchConfigurations` was empty our case. Possibly, we need to spend more time implementing a more general solution. The solution proposed …
> [TT-6737] Starting a subscription without attached data source crashes GW

- pkg/engine/datasource/graphql_datasource/graphql_subscription_client.go
- pkg/graphql/config_factory_federation.go
- pkg/graphql/config_factory_federation_test.go
- pkg/graphql/config_factory_proxy.go
- pkg/graphql/config_factory_proxy_test.go
- pkg/graphql/engine_config_v2.go
- pkg/graphql/engine_config_v2_test.go
- pkg/graphql/subscription.go
This PR adds new subscription types to:
- config generator for proxy-only
- config generator for federation
> add new subscription types to proxy-only and federation cfg generators

- pkg/graphql/engine_config_v2.go
- pkg/graphql/engine_config_v2_test.go
This PR (finally) adds a method to `EngineV2Configuration` to enable single flight.
> add method to enable single flight in engine v2 config

- pkg/engine/resolve/resolve.go
- pkg/engine/resolve/resolve_test.go
return meaningful error message when an int/float is provided to the resolveString func
> meaningful errors for resolveString func

- internal/pkg/unsafebytes/unsafebytes.go
- internal/pkg/unsafebytes/unsafebytes_test.go
- pkg/ast/ast_argument.go
- pkg/ast/ast_object_field.go
- pkg/ast/ast_type.go
- pkg/ast/ast_val_int_value.go
- pkg/ast/ast_value.go
- pkg/astparser/parser.go
- pkg/astvalidation/operation_rule_fragments.go
- pkg/astvalidation/operation_rule_known_arguments.go
- pkg/astvalidation/operation_rule_valid_arguments.go
- pkg/astvalidation/operation_rule_values.go
- pkg/astvalidation/operation_rule_variables_are_input_types.go
- pkg/astvalidation/operation_validation.go
- pkg/astvalidation/operation_validation_test.go
- pkg/astvalidation/reference/testsgo/KnownArgumentNamesRule_test.go
- pkg/astvalidation/reference/testsgo/KnownTypeNamesRule_test.go
- pkg/astvalidation/reference/testsgo/UniqueInputFieldNamesRule_test.go
- pkg/astvalidation/reference/testsgo/ValuesOfCorrectTypeRule_test.go
- pkg/astvalidation/reference/testsgo/VariablesAreInputTypesRule_test.go
- pkg/astvalidation/reference/testsgo/VariablesInAllowedPositionRule_test.go
- pkg/astvalidation/reference/testsgo/harness_test.go
- pkg/astvalidation/reference/testsgo/test_schema.graphql
- pkg/astvisitor/visitor.go
- pkg/operationreport/externalerror.go
* allow integer to be used in place of ID type
* reduce responsibility of valid arguments rule use testify require instead of panic
update test to use proper rules
move some tests in more proper sections
* add position to values
* make variable errors messages compatible with reference tests add location to incompatible types error msg
add initial values error messages draft
* remove skips
* partially refactor values validation - fail in exact places when we have more info about fail reason
* handle unexpected null error
* add more precise enum values error msgs
* fix null as a list value fix single item as a list value
* skip not existing args in valid arguments validation add a check that default arg value has a non null type
* fix arguments validation when variable is placed inside a …
> improve values validation to reflect reference implementation

- pkg/engine/datasource/graphql_datasource/graphql_datasource_test.go
- pkg/engine/plan/plan.go
- pkg/engine/resolve/resolve.go
Currently, when you send the following query for both proxy-only and UDG APIs, the GW panics and the user gets 502 for the query.
```graphql
query {
__typename
}
```
The actual error message is the following:
```json
{
"errors": [
{
"message": "unable to resolve",
"locations": [
{
"line": 2,
"column": 5
}
]
}
],
"data": null
}
```
The `data` is null because no data source is attached to the `__typename`. It's evaluated by this block: https://github.com/TykTechnologies/graphql-go-tools/blob/c2dd74b524578d0653cf7652efba56a19304ebae/pkg/engine/plan/plan.go#L519
Initially, I thought that it would be enough to proxy the request to the upstream. It works for the proxy-only mode but it doesn't work for UDG. 
Consider the following example. I have a dummy REST service that returns `{"temp": …
> [TT-6419] Querying for __typename in any graph causes a 502 error

- pkg/engine/datasource/graphql_datasource/graphql_datasource.go
- pkg/engine/datasource/graphql_datasource/graphql_datasource_test.go
- pkg/engine/datasource/graphql_datasource/graphql_sse_handler.go
- pkg/engine/datasource/graphql_datasource/graphql_sse_handler_test.go
- pkg/engine/datasource/httpclient/httpclient.go
- pkg/engine/plan/plan.go
- pkg/graphql/execution_engine_v2_test.go
This PR contains changes from:
- Custom Scalar Replacement: https://github.com/wundergraph/graphql-go-tools/pull/456
- Add support for requests in SSE Subscriptions: https://github.com/wundergraph/graphql-go-tools/pull/449
- Fix planning variable path: https://github.com/wundergraph/graphql-go-tools/pull/464
Use commit view to review single commits.
> cherry pick changes from wundergraph

- pkg/subscription/context.go
- pkg/subscription/context_test.go
- pkg/subscription/handler.go
- pkg/subscription/handler_test.go
PR for [TT-6137](https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/26?modal=detail&selectedIssue=TT-6137).
Currently, we implement `graphql-ws` protocol for the communication between GW and the clients. This protocol supports running many subscriptions on a single WebSocket connection. It utilizes subscription ids to implement that feature. In our implementation, we don’t consider about the uniqueness of the message ids. 
Our implementation keeps ids per connection. So the ids are not global. See the following code snippet from the library:
**handleStart**:
```go
if executor.OperationType() == ast.OperationTypeSubscription {
ctx := h.subCancellations.Add(id)
go h.startSubscription(ctx, id, executor)
return
}
```
**Add**:
```go
func (sc subscriptionCancellations) Add(id …
```
> [TT-6137] Can't close all subscriptions when more than one are opened

- go.mod
- go.sum
- pkg/asyncapi/asyncapi.go
- pkg/asyncapi/asyncapi_test.go
- pkg/asyncapi/converter.go
- pkg/asyncapi/converter_test.go
- pkg/asyncapi/fixtures/email-service-2.0.0.graphql
- pkg/asyncapi/fixtures/email-service-2.0.0.yaml
- pkg/asyncapi/fixtures/payment-sample-2.0.0.graphql
- pkg/asyncapi/fixtures/payment-sample-2.0.0.yaml
- pkg/asyncapi/fixtures/payment-system-sample-2.2.0.graphql
- pkg/asyncapi/fixtures/payment-system-sample-2.2.0.yaml
- pkg/asyncapi/fixtures/print-service-api-2.0.0.graphql
- pkg/asyncapi/fixtures/print-service-api-2.0.0.yaml
- pkg/asyncapi/fixtures/streetlights-kafka-2.4.0-and-below.graphql
- pkg/asyncapi/fixtures/trading-sample-2.0.0.graphql
- pkg/asyncapi/fixtures/trading-sample-2.0.0.yaml
- pkg/asyncapi/fixtures/user-api-2.0.0.graphql
- pkg/asyncapi/fixtures/user-api-2.0.0.yaml
PR for [TT-7468](https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/26?modal=detail&selectedIssue=TT-7468)
`ImportAsyncAPIDocumentByte` has been added to produce a GraphQL schema from a parsed AsyncAPI document. The implementation uses `introspection.JsonConverter` to build a GraphQL schema. Introspection was used as an intermediate format between GQL and AsyncAPI documents. This way, we avoid implementing a clone of `introspection.JsonConverter` for AsyncAPI. 
A few things to consider:
* `introspection.__TypeKind` is an unexported type but the implementation requires it. As a workaround, I added a function that returns `introspection.TypeRef` directly. We can export `__TypeKind` from the introspection package but this is a breaking change.
* The parsed AsyncAPI document …
> [TT-7468] Configuring UDG Schema based on info parsed from AsyncAPI spec

- pkg/asyncapi/converter.go
- pkg/asyncapi/fixtures/email-service-2.0.0.graphql
- pkg/asyncapi/fixtures/payment-sample-2.0.0.graphql
- pkg/asyncapi/fixtures/payment-system-sample-2.2.0.graphql
- pkg/asyncapi/fixtures/print-service-api-2.0.0.graphql
- pkg/asyncapi/fixtures/streetlights-kafka-2.4.0-and-below.graphql
- pkg/asyncapi/fixtures/trading-sample-2.0.0.graphql
- pkg/asyncapi/fixtures/user-api-2.0.0.graphql
This PR adds Query root type to the schemas produced from AsyncAPI documents. It's a mandatory field. It also has a dummy field because empty types are not allowed.
```graphql
schema {
query: Query
subscription: Subscription
}
type Query {
_: Boolean
}
```
This PR also includes small code organization improvements.
> [TT-7826] Add Query root type

- pkg/engine/resolve/resolve_test.go
- pkg/graphql/execution_engine_v2_test.go
This PR adds tests for single-value array field-mappings. It documents the way how to overcome a situation, where an API always returns an array with a single value in it.
> add tests for single-value array field-mappings

- go.mod
- go.sum
This PR upgrades Masterminds/goutils to `v1.1.1` from `v1.1.0`
- https://tyktech.atlassian.net/browse/TT-8349
- https://dso.docker.com/cve/CVE-2021-4238
> [TT-8349] Upgrade github.com/Masterminds/goutils to v1.1.1

- go.mod
- go.sum
- pkg/openapi/fixtures/v3.0.0/EmployeeApi.graphql
- pkg/openapi/fixtures/v3.0.0/EmployeesApi.graphql
- pkg/openapi/fixtures/v3.0.0/EmployeesApi.yaml
- pkg/openapi/fixtures/v3.0.0/EmployeesApiBasic.graphql
- pkg/openapi/fixtures/v3.0.0/EmployeesApiBasic.yaml
- pkg/openapi/fixtures/v3.0.0/example_oas3.graphql
- pkg/openapi/fixtures/v3.0.0/example_oas3.json
- pkg/openapi/fixtures/v3.0.0/example_oas7.graphql
- pkg/openapi/fixtures/v3.0.0/example_oas7.json
- pkg/openapi/fixtures/v3.0.0/petstore-expanded.graphql
- pkg/openapi/fixtures/v3.0.0/petstore-expanded.yaml
- pkg/openapi/fixtures/v3.0.0/petstore.graphql
- pkg/openapi/fixtures/v3.0.0/petstore.yaml
- pkg/openapi/openapi.go
- pkg/openapi/openapi_test.go
This PR implements an OpenAPI to GraphQL converter. Currently, it only supports OpenAPI v3.0.0 `getkin/kin-openapi` provides a different parser for OpenAPI 2.0.0 but it is based on OpenAPI 3.0.0. v2.0.0 support should be planned and tested separately. 
Known issues and missing features:
* Cannot properly handle field arguments if the type is an array.
* Doesn't support [links](https://swagger.io/docs/specification/links/).
* Doesn't support non-null fields.
* Doesn't support [HTTP response ranges](https://swagger.io/docs/specification/describing-responses/?sbsearch=range)(for example, 2XX). 
* It's not clear how to handle non-JSON responses, for example, `application/geo+json` or `text/plain`.
Example documents and their GraphQL counterparts can be found under `openapi/fixtures/v3.0.0`. …
> [TT-7465] Parsing information needed for UDG config from OpenAPI-3 spec

- pkg/engine/resolve/inputtemplate.go
- pkg/engine/resolve/inputtemplate_test.go
- pkg/graphql/execution_engine_v2_test.go
- pkg/graphqljsonschema/jsonschema_test.go
This PR fixes an inconsistent behavior when using `null` in a variable for a required type (e.g. `String!`)
> fix validation skipping for null on scalars

- pkg/engine/resolve/resolve.go
PR from WG: https://github.com/wundergraph/graphql-go-tools/pull/518
> fix: resolve, do not resolve fetch if ctx is cancelled (#518)

- pkg/graphql/execution_engine_v2.go
- pkg/graphql/execution_engine_v2_custom.go
- pkg/graphql/execution_engine_v2_custom_test.go
- pkg/graphql/execution_engine_v2_test.go
Changes in this PR are based on @buraksezer 's awesome research in this commit: https://github.com/TykTechnologies/graphql-go-tools/commit/23f7686189d155642aaf2678e0e3a28db37b57c5
This PR introduces interfaces for a `CustomExecutionEngineV2` including execution stages.
By introducing those changes it will be possible to provide its own `ExecutionEngineV2` or decorate the already implemented `ExecutionEngineV2`.
Changes:
- added a benchmark test for `ExecutionEngineV2.Execute` to track performance impacts with this change (none so far)
- introduced the following interfaces:
- `CustomExecutionEngineV2NormalizerStage` (optional)
- `CustomExecutionEngineV2ValidatorStage` (optional)
- `CustomExecutionEngineV2ResolverStage` (required)
- `ExecutionEngineV2Executor`
- added a default …
> introduce CustomExecutionEngineV2

- pkg/graphql/request.go
- pkg/graphql/request_test.go
This PR adds a `MarshalRequest` and a `MarshalRequestString` function to the `graphql` package.
It also adds `omitempty` to `OperationName` and `Variables` fields.
> add MarshalRequest functions and omit empties

- pkg/openapi/fixtures/v3.0.0/EmployeesApi.graphql
- pkg/openapi/fixtures/v3.0.0/EmployeesApiBasic.graphql
- pkg/openapi/fixtures/v3.0.0/example_oas3.graphql
- pkg/openapi/fixtures/v3.0.0/example_oas7.graphql
- pkg/openapi/fixtures/v3.0.0/petstore-expanded.graphql
- pkg/openapi/fixtures/v3.0.0/petstore.graphql
- pkg/openapi/openapi.go
PR for [TT-8528](https://tyktech.atlassian.net/browse/TT-8528)
Now, we can handle non-nullable fields properly. There was also a minor bug in a function that generates mutation type. It was swallowing the parameters if a request body defined for the same operation id. This bug has also been fixed.
[TT-8528]: https://tyktech.atlassian.net/browse/TT-8528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-8528] Improper handling of non-nullable fields in OpenAPI

- pkg/graphql/execution_engine_v2.go
- pkg/graphql/execution_engine_v2_custom.go
- pkg/graphql/input_validation.go
- pkg/graphql/input_validation_test.go
- pkg/operationreport/externalerror.go
- pkg/variablevalidator/variablevalidator.go
- pkg/variablevalidator/variablevalidator_test.go
This PR adds a separate module called variable validation, this module will be added as a separate stage in the graphql execution
[TT-8944](https://tyktech.atlassian.net/browse/TT-8944)
[TT-8944]: https://tyktech.atlassian.net/browse/TT-8944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-8944] Refactor: move variable validation logic to separate step

- pkg/variablevalidator/variablevalidator.go
- pkg/variablevalidator/variablevalidator_test.go
This fixes an edge case where the variables passed is either unsanitized json or invalid json.
> [TT-8944]: added and fix case where variable is unsanitized json

- pkg/engine/datasource/introspection_datasource/config_factory.go
- pkg/engine/datasource/introspection_datasource/fixtures/schema_introspection_with_custom_root_operation_types.golden
- pkg/engine/datasource/introspection_datasource/planner_test.go
- pkg/engine/datasource/introspection_datasource/source_test.go
- pkg/introspection/testdata/schema_with_custom_root_operation_types.graphql
This PR fixes an introspection issue when custom root operation types are defined, e.g.
```
schema {
query: CustomQuery
mutation: CustomMutation
subscription: CustomSubscription
}
type CustomQuery {
friend: String
}
type CustomMutation {
addFriend: Boolean
}
type CustomSubscription {
lastAddedFriend: String
}
```
> fix introspection not working for custom root operation types

- pkg/engine/datasource/rest_datasource/rest_datasource.go
- pkg/engine/datasource/rest_datasource/rest_datasource_test.go
THis ticket fixes an issue where the input generated for the rest datasource wraps query params that are fetched from arguments with quotes, thereby breaking the URL generated down the execution pipeline
> [TT-8526] fix issue where query params of type int and array are wrapped with quotes

- pkg/graphql/input_validation.go
- pkg/graphql/input_validation_test.go
- pkg/operationreport/externalerror.go
- pkg/variablevalidator/variablevalidator.go
- pkg/variablevalidator/variablevalidator_test.go
Moved the variable validation logic to a separate execution step to allow for returning a proper error.
> [TT-8944]: Moved the variable validation logic to 5.1

- pkg/subscription/engine.go
- pkg/subscription/engine_test.go
- pkg/subscription/websocket/protocol_graphql_ws.go
- pkg/subscription/websocket/protocol_graphql_ws_test.go
This PR closes the connection in the graphql-ws protocol implementation if the backoff threshold for the subscription execution has been hit
> [TT-9882]: close graphql-ws protocol coonnections on error timeout

- pkg/openapi/fixtures/v3.0.0/example_oas7.graphql
- pkg/openapi/openapi.go
This PR fixes an issue where it could happen that the OAS converter picks up a full type without all the details before reaching the full definition. This caused the converter to not pick up descriptions.
To fix this I introduced an details cache that only tracks if a detail is already stored or not.
> fix full type details not being able to be updated

- pkg/subscription/engine.go
- pkg/subscription/engine_test.go
- pkg/subscription/handler.go
This PR fixes an issue where races were occurring in the subscription backoff tests.
Also an issues was fixed where context canceling was not propagated to the backoff loop.
> fix race issues in subscription backoff

- pkg/openapi/fixtures/v3.0.0/carts-api-oas.graphql
- pkg/openapi/fixtures/v3.0.0/carts-api-oas.yaml
- pkg/openapi/openapi.go
- pkg/openapi/openapi_test.go
PR for [TT-10483](https://tyktech.atlassian.net/browse/TT-10483)
OpenAPI-to-GraphQL converter can now create a GraphQL type from an unnamed object and create an array of that type.
```yaml
components:
schemas:
Cart:
type: object
properties:
id:
type: integer
products:
type: array
items:
type: object
properties:
product_id:
type: integer
```
Previously, we could not produce the correct GQL types  for `Cart`. With this PR, we can produce the following types:
```graphql
type Cart {
id: Int
products: [ProductsListItem]
}
type ProductsListItem {
productId: Int
}
```
`ProductsListItem` type name has been produced by our converter tool. The naming style has been borrowed from [IBM/openapi-to-graphql](https://github.com/IBM/openapi-to-graphql) tool. 
[TT-10483]: …
> [TT-10483] Handle arrays of objects in OpenAPI documents 

- v2/pkg/openapi/fixtures/v3.0.0/carts-api-oas_tt_10604.graphql
- v2/pkg/openapi/fixtures/v3.0.0/carts-api-oas_tt_10604.yaml
- v2/pkg/openapi/openapi.go
- v2/pkg/openapi/openapi_test.go
This PR copies the latest OAS converter changes to the `v2` folder. See https://github.com/TykTechnologies/graphql-go-tools/pull/404
> [TT-10604] Handling arrays of objects in endpoint responses - engine v2

- pkg/openapi/fixtures/v3.0.0/enum-component-mutation.graphql
- pkg/openapi/fixtures/v3.0.0/enums-mutation.graphql
- pkg/openapi/openapi.go
- v2/pkg/openapi/fixtures/v3.0.0/enum-component-mutation.graphql
- v2/pkg/openapi/fixtures/v3.0.0/enums-mutation.graphql
- v2/pkg/openapi/openapi.go
This PR adds a placeholder Query type if there is no query definition in the source OpenAPI document. The behavior, including the `QueryPlaceholder` type name, is borrowed from IBM's openapi-to-graphql tool.
> [TT-10697] Add placeholder Schema and Query to OpenAPI and graphql fixtures

- pkg/openapi/field.go
- pkg/openapi/fixtures/v3.0.0/enum-properties.graphql
- pkg/openapi/fixtures/v3.0.0/enum-properties.yaml
- pkg/openapi/openapi_test.go
- v2/pkg/openapi/field.go
- v2/pkg/openapi/fixtures/v3.0.0/enum-properties.graphql
- v2/pkg/openapi/fixtures/v3.0.0/enum-properties.yaml
- v2/pkg/openapi/openapi_test.go
Fixes a bug if an enum field is defined as a component's property. See https://tyktech.atlassian.net/browse/TT-10697?focusedCommentId=48290 for the details.
> [TT-10697] Handle enum definition if the enum field is defined as a property

- pkg/graphql/request.go
- pkg/graphql/request_test.go
- pkg/graphql/validation.go
- pkg/graphql/validation_test.go
This PR
modifies the Request.go file to:
add isValidated boolean attribute to the request struct
add the IsValidated method to return the value of isValidated
modifies the validation.go file to: 
set isValidated to true
This is being done to simplify removing normalization and validation from the graphql engine in the gateway.
> add is validated attribute and method to request

- pkg/openapi/mutation.go
- pkg/openapi/openapi_test.go
- pkg/openapi/query.go
- pkg/openapi/utils.go
- v2/pkg/openapi/mutation.go
- v2/pkg/openapi/openapi_test.go
- v2/pkg/openapi/query.go
- v2/pkg/openapi/utils.go
Tyk GW uses `github.com/iancoleman/strcase v0.3.0` but graphql-go-tools uses version `v0.2.0`. The OpenAPI translator uses the `strcase.ToCamel` method to process type names. This method in the newer version converts `JSON` to `Json`, while the older version doesn't do that. It simply returns the same string. 
This PR fixes this problem and checks the type name before further processing. We don't need to call `ToCamel` method if the type name is a predefined scalar type. 
We don't catch this error with our test suite because when graphql-go-tools is imported from Tyk GW, the newer version of the dependency is used. It may be a good idea to upgrade `github.com/iancoleman/strcase` to `v0.3.0` from `v0.2.0` for compatibility. I do not prefer to do that in this PR because different components …
> [TT-11071] OAS converter fails when return type is JSON

- pkg/openapi/fixtures/v3.0.0/status-code-ranges.graphql
- pkg/openapi/fixtures/v3.0.0/status-code-ranges.yaml
- pkg/openapi/fulltype.go
- pkg/openapi/mutation.go
- pkg/openapi/openapi.go
- pkg/openapi/openapi_test.go
- pkg/openapi/query.go
- pkg/openapi/utils.go
- pkg/openapi/utils_test.go
- v2/pkg/openapi/fixtures/v3.0.0/status-code-ranges.graphql
- v2/pkg/openapi/fixtures/v3.0.0/status-code-ranges.yaml
- v2/pkg/openapi/fulltype.go
- v2/pkg/openapi/mutation.go
- v2/pkg/openapi/openapi_test.go
- v2/pkg/openapi/query.go
- v2/pkg/openapi/utils.go
- v2/pkg/openapi/utils_test.go
PR for https://tyktech.atlassian.net/browse/TT-11069
This update extends the handling of status codes in OpenAPI testing by including support for status code ranges. The implementation converts ranges to status codes in integer type and can also convert a status code to a range. 
The changes will be copied to the `v2` folder after approval.
> [TT-11069] Add support for status code ranges in OpenAPI

- pkg/openapi/fixtures/v3.0.0/status-code-precedence.graphql
- pkg/openapi/fixtures/v3.0.0/status-code-precedence.yaml
- pkg/openapi/fixtures/v3.0.0/status-code-valid-responses.graphql
- pkg/openapi/fixtures/v3.0.0/status-code-valid-responses.yaml
- pkg/openapi/fulltype.go
- pkg/openapi/mutation.go
- pkg/openapi/openapi_test.go
- pkg/openapi/query.go
- pkg/openapi/utils.go
- pkg/openapi/utils_test.go
This PR fixes bad handling of responses if an HTTP status code range and explicit code definition are used at the same time. The OpenAPI specification is clear about this:
> To define a range of response codes, you may use the following range definitions: 1XX, 2XX, 3XX, 4XX, and 5XX. If a response range is defined using an explicit code, the explicit code definition takes precedence over the range definition for that code.
Now, the OpenAPI-to-GraphQL translator picks the explicit code definition over the range definition. 
Suppose the OpenAPI document contains multiple possible successful response objects (HTTP code 200-299 or 2XX). Only one can be chosen. It selects the first response object with the successful status code (200-299). The response object with the HTTP code 200 will be …
> [TT-11249] OAS-to-GQL translator adds the same field many times

- pkg/astvalidation/operation_rule_valid_arguments.go
- pkg/astvalidation/operation_validation_test.go
- pkg/operationreport/externalerror.go
- v2/pkg/astvalidation/operation_rule_valid_arguments.go
- v2/pkg/astvalidation/operation_validation_test.go
- v2/pkg/operationreport/externalerror.go
This PR fixes TT-11295. The problem was not related to the Persist GQL feature. The library fails to validate a specifically crafted query in which variables are not defined in the operation. 
An example query: 
```graphql
query Analytics ($startMonth: String, $startYear: String!, $endDay: String!, $endMonth: String, $endYear: String!){
analytics(
EndDay: $endDay
EndMonth: $endMonth
EndYear: $endYear
StartDay: $startDay
StartMonth: $startMonth
StartYear: $startYear
) {
data {
error
hits
success
id {
alias
key
additional_data {
data {
meta_data {
department
}
tags
}
}
}
}
}
}
```
`$startDay` is not defined in the operation `Analytics`. The library panics when you try to run this query. With this PR, it returns the following error:
```json:
{
"message": "Variable \"$startDay\" is not …
```
> [TT-11295] Gateway Panics when arguments are not defined in operation section

- v2/pkg/engine/datasource/rest_datasource/rest_datasource.go
- v2/pkg/engine/datasource/rest_datasource/rest_datasource_test.go
- v2/pkg/engine/plan/planner.go
- v2/pkg/graphql/execution_engine_v2_test.go
- v2/pkg/variablesvalidation/variablesvalidation.go
This PR adds the rest datasource to the v2/ of the engine, it also includes some changes to ensure it works with the new v2 engine, these changes will need to be reflected in the apidef being passed to the engine
[TT-10292](https://tyktech.atlassian.net/browse/TT-10291)
[TT-10292]: https://tyktech.atlassian.net/browse/TT-10292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-10292]: Add rest datasource

- pkg/engine/datasource/graphql_datasource/graphql_datasource.go
- pkg/engine/datasource/graphql_datasource/graphql_datasource_test.go
- pkg/graphql/execution_engine_v2_test.go
This PR fixes an issue when a nested data source is lonely.
It is built on top of @buraksezer 's research.
How does it work?
The GraphQL data source planner has been slightly modified and will before printing the upstream query check for fields that require selections.
Example:
```
{ countries }
```
During this check, it will realize that `countries` is missing the selections and will therefore add the `__typename` selection field. This will result in following upstream query:
```
{ countries { __typename } }
```
With that the upstream is valid again.
> should resolve with a nested lonely data source (TT-9884)

- pkg/engine/resolve/variable.go
- pkg/postprocess/datasourceinput.go
- pkg/postprocess/datasourceinput_test.go
This PR fixes [TT-12313](https://tyktech.atlassian.net/browse/TT-12313) and [TT-12222](https://tyktech.atlassian.net/browse/TT-12222).
**TT-12313:**
Variables in an input template were evaluating as strings by default. It may produce invalid JSON as rendered input data. Now it protects the original data type. 
See the following:
A valid input template, variables in the `variables` object are strings because this is a valid JSON.
```json
{
"body": {
"variables": {
"id": "$$0$$",
"theme_ids": "$$1$$",
"abc": "$$2$$"
},
"query": "query ProductById($id: Int, $theme_ids: [String], $abc: String) {\n    product(id: $id, theme_ids: $theme_ids, abc: $abc) {\n        id\n        name\n        info\n        price\n        theme_ids\n    }\n}"
},
"method": "POST",
"url": …
```
> [TT-12313] UDG APIs - Array of strings in variables gets transformed to one big string by engine

- pkg/postprocess/datasourceinput.go
- pkg/postprocess/datasourceinput_test.go
See https://tyktech.atlassian.net/browse/TT-12503 and https://tyktech.atlassian.net/browse/TT-12313 for detailed description of the problem.
Now, we render the following variables as a String.
* String
* NotExist
* Unknown
graphql-go-tools assigns `NotExists` type to `ID` type. ID type should be rendered as String. 
Related part of the spec: https://spec.graphql.org/October2021/#sec-ID
> [TT-12503] Render ID type as a String

- pkg/astnormalization/input_coercion_for_list.go
- pkg/graphql/normalization_test.go
PR for https://tyktech.atlassian.net/browse/TT-13608 
An analysis can be found here: https://tyktech.atlassian.net/browse/TT-13608?focusedCommentId=90515
Basically, input coercion for list visitor has been failing to infer the type of a node in the GQL operation and leaves the variable as-is instead of making a list from a object. 
This lead to raise `mismatched input value` error in `inputFieldDefaultInjectionVisitor` because the desired type was a `list` but the type in the `variables` JSON was an `object`. 
Inferring variable definition by its name not the value fixes the problem. 
I didn't copied the fix to `v2` folder because it already has the fix.
> [TT-13608] Issues with custom scalar in query variable
